// External Dependencies
import { Inter } from "next/font/google";

// Relative Dependencies
import "~/styles/globals.css";
import Providers from "~/components/ui/providers/Providers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Providers>
        <body className={`font-sans ${inter.variable}`}>{children}</body>
      </Providers>
    </html>
  );
}
